[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 15

[db.pooler]
enabled = false

[auth]
enabled = true
site_url = "https://churchonapp.com"
additional_redirect_urls = ["churchonapp://callback", "https://churchonapp.com/auth/callback", "https://churchonapp.com", "https://churchonapp.pages.dev"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_confirmations = false

[storage]
enabled = true

[edge_runtime]
enabled = true
policy = "per_worker"

[analytics]
enabled = false

[vector]
enabled = false
max_buckets = 10
max_indexes = 5
[vector.buckets]

[experimental]
orioledb_version = ""
