-- Clean existing seed questions to avoid duplicates if re-run
DELETE FROM public.quiz_questions WHERE difficulty = 'Medium' AND points BETWEEN 10 AND 100;

INSERT INTO public.quiz_questions (question, type, points, category, correct_answer, options, is_arena, scripture_reference) VALUES
('First man?', 'rapid_fire', 20, 'People', 0, '[]'::jsonb, false, null),
('First woman?', 'rapid_fire', 20, 'People', 0, '[]'::jsonb, false, null),
('Built the ark?', 'rapid_fire', 20, 'History', 0, '[]'::jsonb, false, null),
('Oldest man in Bible?', 'rapid_fire', 20, 'People', 0, '[]'::jsonb, false, null),
('Father of many nations?', 'rapid_fire', 20, 'People', 0, '[]'::jsonb, false, null),
('Wife of Abraham?', 'rapid_fire', 20, 'People', 0, '[]'::jsonb, false, null),
('Abraham’s promised son?', 'rapid_fire', 20, 'People', 0, '[]'::jsonb, false, null),
('Who sold his birthright?', 'rapid_fire', 20, 'People', 0, '[]'::jsonb, false, null),
('Wrestled effectively with God?', 'rapid_fire', 20, 'History', 0, '[]'::jsonb, false, null),
('Reviewer of dreams in Egypt?', 'rapid_fire', 20, 'People', 0, '[]'::jsonb, false, null),
('Saved from river as baby?', 'rapid_fire', 20, 'People', 0, '[]'::jsonb, false, null),
('God spoke from a...?', 'rapid_fire', 20, 'History', 0, '[]'::jsonb, false, null),
('Slayer of Goliath?', 'rapid_fire', 20, 'People', 0, '[]'::jsonb, false, null),
('First King of Israel?', 'rapid_fire', 20, 'History', 0, '[]'::jsonb, false, null),
('Wisest Bible King?', 'rapid_fire', 20, 'People', 0, '[]'::jsonb, false, null),
('Prophet taken by chariot?', 'rapid_fire', 20, 'Prophecy', 0, '[]'::jsonb, false, null),
('Received double portion?', 'rapid_fire', 20, 'Prophecy', 0, '[]'::jsonb, false, null),
('Swallowed by big fish?', 'rapid_fire', 20, 'History', 0, '[]'::jsonb, false, null),
('Weeping Prophet?', 'rapid_fire', 20, 'Prophecy', 0, '[]'::jsonb, false, null),
('Survived Lion’s Den?', 'rapid_fire', 20, 'People', 0, '[]'::jsonb, false, null),
('Queen who saved Jews?', 'rapid_fire', 20, 'History', 0, '[]'::jsonb, false, null),
('Who rebuilt walls?', 'rapid_fire', 20, 'History', 0, '[]'::jsonb, false, null),
('Where was Jesus born?', 'rapid_fire', 20, 'History', 0, '[]'::jsonb, false, null),
('Who baptized Jesus?', 'rapid_fire', 20, 'People', 0, '[]'::jsonb, false, null),
('Betrayer of Christ?', 'rapid_fire', 20, 'People', 0, '[]'::jsonb, false, null),
('Denied Jesus 3 times?', 'rapid_fire', 20, 'People', 0, '[]'::jsonb, false, null),
('Doubted Jesus?', 'rapid_fire', 20, 'People', 0, '[]'::jsonb, false, null),
('Persecutor turned Apostle?', 'rapid_fire', 20, 'People', 0, '[]'::jsonb, false, null),
('First Christian Martyr?', 'rapid_fire', 20, 'History', 0, '[]'::jsonb, false, null),
('Wrote Revelation?', 'rapid_fire', 20, 'Prophecy', 0, '[]'::jsonb, false, null),
('Shortest verse?', 'rapid_fire', 20, 'General', 0, '[]'::jsonb, false, null),
('Number of Disciples?', 'rapid_fire', 20, 'General', 0, '[]'::jsonb, false, null),
('Fruits of the Spirit?', 'rapid_fire', 20, 'Teachings', 0, '[]'::jsonb, false, null),
('Commandments count?', 'rapid_fire', 20, 'Teachings', 0, '[]'::jsonb, false, null),
('Root of all evil?', 'rapid_fire', 20, 'Teachings', 0, '[]'::jsonb, false, null),
('Greatest virtue?', 'rapid_fire', 20, 'Teachings', 0, '[]'::jsonb, false, null),
('Salary of sin?', 'rapid_fire', 20, 'Teachings', 0, '[]'::jsonb, false, null),
('First Miracle?', 'rapid_fire', 20, 'History', 0, '[]'::jsonb, false, null),
('Quote John 3:16', 'verbatim', 60, 'General', 0, '[]'::jsonb, false, 'John 3:16'),
('Quote Philippians 4:13', 'verbatim', 40, 'General', 0, '[]'::jsonb, false, 'Philippians 4:13'),
('Who led Israel after Moses?', 'choice', 10, 'History', 1, '["Aaron", "Joshua", "Caleb", "Hur"]'::jsonb, false, null),
('Which city walls fell down?', 'choice', 10, 'History', 2, '["Babylon", "Jerusalem", "Jericho", "Nineveh"]'::jsonb, false, null),
('Who was the strongest man?', 'choice', 10, 'People', 2, '["Goliath", "David", "Samson", "Boaz"]'::jsonb, false, null),
('Who climbed a tree to see Jesus?', 'choice', 10, 'People', 1, '["Matthew", "Zacchaeus", "Bartimaeus", "Lazarus"]'::jsonb, false, null),
('The Sermon on the...?', 'choice', 10, 'Teachings', 2, '["Plain", "Valley", "Mount", "Sea"]'::jsonb, false, null),
('Who walked on water?', 'choice', 10, 'History', 2, '["James", "John", "Peter", "Andrew"]'::jsonb, false, null),
('Who lived on locusts and honey?', 'choice', 10, 'People', 1, '["Elijah", "John the Baptist", "Samson", "Paul"]'::jsonb, false, null),
('What sea did Moses part?', 'choice', 10, 'History', 1, '["Dead Sea", "Red Sea", "Mediterranean", "Galilee"]'::jsonb, false, null),
('Who wrote the most Psalms?', 'choice', 10, 'General', 2, '["Solomon", "Asaph", "David", "Moses"]'::jsonb, false, null),
('Which disciple was a doctor?', 'choice', 10, 'People', 0, '["Luke", "Mark", "Matthew", "John"]'::jsonb, false, null),
('Who had a coat of many colors?', 'choice', 10, 'People', 1, '["Benjamin", "Joseph", "Reuben", "Dan"]'::jsonb, false, null),
('What is the Armor of God for?', 'choice', 30, 'Arena', 1, '["Attack", "Defense", "Status", "Decoration"]'::jsonb, true, null),
('Sword of the Spirit is...?', 'choice', 30, 'Arena', 2, '["Prayer", "Faith", "Word of God", "Truth"]'::jsonb, true, null),
('Shield of...?', 'choice', 30, 'Arena', 1, '["Truth", "Faith", "Peace", "Salvation"]'::jsonb, true, null),
('Belt of...?', 'choice', 30, 'Arena', 0, '["Truth", "Love", "Justice", "Mercy"]'::jsonb, true, null);
