org.gradle.jvmargs=-Xmx3G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError -Dhttps.protocols=TLSv1.2,TLSv1.3 -Djdk.tls.client.protocols=TLSv1.2,TLSv1.3 -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false
android.useAndroidX=true
android.enableJetifier=true
android.enableR8.fullMode=true
org.gradle.caching=false
kotlin.incremental=false
