import 'package:flutter/foundation.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import 'lyrics_service.dart';

/// Item 7 — turn a worship setlist into a printable / shareable PDF.
///
/// The table (`worship_setlists`) has existed since 20261226 with no output
/// surface at all, so this is the cheapest visible win in the whole ChMS
/// backlog: one button, and the musicians get a sheet they can actually hold.
class SetlistPdfService {
  const SetlistPdfService();

  static const _brandYellow = PdfColor.fromInt(0xFFFFDA03);
  static const _ink = PdfColor.fromInt(0xFF1A1A1A);

  /// Build the setlist PDF. [churchName] is printed in the header so the sheet
  /// is self-identifying when a musician carries it between rooms.
  Future<Uint8List> build({
    required Setlist setlist,
    required List<WorshipLyric> songs,
    String? churchName,
  }) async {
    final doc = pw.Document(
      title: setlist.title,
      author: churchName ?? 'Church On App',
    );

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (ctx) => [
          _header(setlist, churchName),
          pw.SizedBox(height: 14),
          _rule(),
          pw.SizedBox(height: 14),
          if (songs.isEmpty)
            pw.Text('No songs on this setlist yet.',
                style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey700))
          else
            ..._songRows(songs),
          pw.SizedBox(height: 18),
          _rule(),
          pw.SizedBox(height: 8),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Generated by Church On App',
                style: const pw.TextStyle(
                    fontSize: 8, color: PdfColors.grey600),
              ),
              pw.Text(
                '${songs.length} song${songs.length == 1 ? '' : 's'}',
                style: const pw.TextStyle(
                    fontSize: 8, color: PdfColors.grey600),
              ),
            ],
          ),
        ],
      ),
    );

    return doc.save();
  }

  pw.Widget _header(Setlist setlist, String? churchName) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        if (churchName != null && churchName.isNotEmpty)
          pw.Text(
            churchName.toUpperCase(),
            style: pw.TextStyle(
              fontSize: 9,
              letterSpacing: 1.2,
              color: PdfColors.grey700,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        pw.SizedBox(height: 4),
        pw.Text(
          setlist.title,
          style: pw.TextStyle(
            fontSize: 20,
            fontWeight: pw.FontWeight.bold,
            color: _ink,
          ),
        ),
        pw.SizedBox(height: 3),
        pw.Row(
          children: [
            if (_dateLabel(setlist.serviceDate) != null) ...[
              pw.Text(
                _dateLabel(setlist.serviceDate)!,
                style: const pw.TextStyle(
                    fontSize: 10, color: PdfColors.grey800),
              ),
              pw.SizedBox(width: 10),
            ],
            pw.Container(
              padding:
                  const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 2),
              decoration: pw.BoxDecoration(
                color: _brandYellow,
                borderRadius: pw.BorderRadius.circular(3),
              ),
              child: pw.Text(
                'SETLIST',
                style: pw.TextStyle(
                  fontSize: 8,
                  fontWeight: pw.FontWeight.bold,
                  color: _ink,
                ),
              ),
            ),
          ],
        ),
      ],
    );
  }

  pw.Widget _rule() => pw.Container(height: 2, color: _brandYellow);

  /// One row per song with a generous lyric column — this is the part the
  /// musician actually reads from, so it gets the most space.
  List<pw.Widget> _songRows(List<WorshipLyric> songs) {
    final out = <pw.Widget>[];
    for (var i = 0; i < songs.length; i++) {
      final s = songs[i];
      out.add(
        pw.Container(
          margin: const pw.EdgeInsets.only(bottom: 12),
          padding: const pw.EdgeInsets.only(left: 8),
          decoration: const pw.BoxDecoration(
            border: pw.Border(
              left: pw.BorderSide(color: _brandYellow, width: 3),
            ),
          ),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Row(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Container(
                    width: 18,
                    height: 18,
                    alignment: pw.Alignment.center,
                    decoration: pw.BoxDecoration(
                      color: _ink,
                      borderRadius: pw.BorderRadius.circular(9),
                    ),
                    child: pw.Text(
                      '${i + 1}',
                      style: pw.TextStyle(
                        fontSize: 9,
                        color: PdfColors.white,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                  ),
                  pw.SizedBox(width: 8),
                  pw.Expanded(
                    child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text(
                          s.title,
                          style: pw.TextStyle(
                            fontSize: 12,
                            fontWeight: pw.FontWeight.bold,
                            color: _ink,
                          ),
                        ),
                        if (s.artist.isNotEmpty)
                          pw.Text(
                            s.artist,
                            style: const pw.TextStyle(
                                fontSize: 9, color: PdfColors.grey700),
                          ),
                      ],
                    ),
                  ),
                ],
              ),
              if (s.lyrics.trim().isNotEmpty) ...[
                pw.SizedBox(height: 6),
                pw.Text(
                  s.lyrics.trim(),
                  style: const pw.TextStyle(
                    fontSize: 9.5,
                    lineSpacing: 1.6,
                    color: PdfColors.grey900,
                  ),
                ),
              ],
            ],
          ),
        ),
      );
    }
    return out;
  }

  /// `Setlist.serviceDate` is a String (the model's own type), so format it
  /// defensively and skip the line when it cannot be parsed.
  static String? _dateLabel(String? raw) {
    if (raw == null || raw.trim().isEmpty) return null;
    final d = DateTime.tryParse(raw.trim());
    if (d == null) return raw.trim();
    return _formatDate(d);
  }

  static String _formatDate(DateTime d) {
    const months = [
      'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
    ];
    return '${d.day} ${months[d.month - 1]} ${d.year}';
  }

  /// Share the PDF with the platform share sheet (WhatsApp, email, Drive…).
  Future<void> share({
    required Setlist setlist,
    required List<WorshipLyric> songs,
    String? churchName,
  }) async {
    final bytes = await build(
        setlist: setlist, songs: songs, churchName: churchName);
    await Printing.sharePdf(
      bytes: bytes,
      filename: '${_safe(setlist.title)}.pdf',
    );
  }

  /// Send straight to a connected printer (PWA / Android print service).
  Future<void> print({
    required Setlist setlist,
    required List<WorshipLyric> songs,
    String? churchName,
  }) async {
    final bytes = await build(
        setlist: setlist, songs: songs, churchName: churchName);
    await Printing.layoutPdf(
      onLayout: (_) async => bytes,
      name: _safe(setlist.title),
    );
  }

  static String _safe(String s) =>
      s.replaceAll(RegExp(r'[^A-Za-z0-9 _-]'), '').trim().replaceAll(' ', '_');
}
