-- ALTER events TABLE FOR SPEAKER, DATES RANGE AND MOMO ROUTING DETAILS
ALTER TABLE events ADD COLUMN IF NOT EXISTS organizer_momo_phone TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS organizer_momo_name TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS speakers TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS end_date TIMESTAMP WITH TIME ZONE;
