ALTER TABLE social_posts ADD COLUMN IF NOT EXISTS prophetic_weight DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE social_posts ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'general';
ALTER TABLE social_posts ADD COLUMN IF NOT EXISTS is_moderated BOOLEAN DEFAULT FALSE;
