-- ============================================================================
-- 20261207_daily_verse_pool_expansion.sql
-- Verse of the Day — pool expansion (additive, idempotent).
--
-- WHY:
--   * `20261201_daily_verse_pool.sql` seeded 166 curated verses. That gives a
--     ~5.5 month cycle, so a daily user sees repeats within a year.
--   * The user asked for AT LEAST ~400 verses so the rotation stays fresh for
--     over a year. This migration adds whole new themed groups on top of the
--     existing set (triumph/victory, joy, love, peace, hope, strength,
--     gratitude, protection, provision, healing, guidance, patience, kindness,
--     faithfulness, self-control, gentleness, forgiveness, courage, rest, new
--     beginnings, seasons, thanksgiving, praise, trusting God, overcoming
--     fear, perseverance, wisdom and unity).
--
-- RULES (same as the base pool):
--   * COMPLETE KJV sense-units — never a contextless fragment.
--   * Correct reference formatting; `book/chapter/verse` feed the audio link
--     (`kjvR2AudioUrlForReference` normalizes "Psalm" → "Psalms").
--   * Idempotent: ON CONFLICT (reference) DO NOTHING, so re-running is safe and
--     existing rows are never overwritten.
-- ============================================================================

INSERT INTO public.daily_verse_pool (reference, verse_text, theme, book, chapter, verse) VALUES
-- HEALING
('Exodus 15:26', $v$And said, If thou wilt diligently hearken to the voice of the LORD thy God, and wilt do that which is right in his sight, and wilt give ear to his commandments, and keep all his statutes, I will put none of these diseases upon thee, which I have brought upon the Egyptians: for I am the LORD that healeth thee.$v$, 'healing', 'Exodus', 15, 26),
('Psalm 103:3', $v$Who forgiveth all thine iniquities; who healeth all thy diseases;$v$, 'healing', 'Psalm', 103, 3),
('Isaiah 53:5', $v$But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed.$v$, 'healing', 'Isaiah', 53, 5),
('Jeremiah 17:14', $v$Heal me, O LORD, and I shall be healed; save me, and I shall be saved: for thou art my praise.$v$, 'healing', 'Jeremiah', 17, 14),
('Jeremiah 30:17', $v$For I will restore health unto thee, and I will heal thee of thy wounds, saith the LORD; because they called thee an Outcast, saying, This is Zion, whom no man seeketh after.$v$, 'healing', 'Jeremiah', 30, 17),
('Matthew 8:17', $v$That it might be fulfilled which was spoken by Esaias the prophet, saying, Himself took our infirmities, and bare our sicknesses.$v$, 'healing', 'Matthew', 8, 17),
('1 Peter 2:24', $v$Who his own self bare our sins in his own body on the tree, that we, being dead to sins, should live unto righteousness: by whose stripes ye were healed.$v$, 'healing', '1 Peter', 2, 24),
('James 5:15', $v$And the prayer of faith shall save the sick, and the Lord shall raise him up; and if he have committed sins, they shall be forgiven him.$v$, 'healing', 'James', 5, 15),
('James 5:16', $v$Confess your faults one to another, and pray one for another, that ye may be healed. The effectual fervent prayer of a righteous man availeth much.$v$, 'healing', 'James', 5, 16),
('Psalm 107:20', $v$He sent his word, and healed them, and delivered them from their destructions.$v$, 'healing', 'Psalm', 107, 20),
('Proverbs 17:22', $v$A merry heart doeth good like a medicine: but a broken spirit drieth the bones.$v$, 'healing', 'Proverbs', 17, 22),
('Psalm 30:2', $v$O LORD my God, I cried unto thee, and thou hast healed me.$v$, 'healing', 'Psalm', 30, 2),
-- PATIENCE
('Ecclesiastes 7:8', $v$Better is the end of a thing than the beginning thereof: and the patient in spirit is better than the proud in spirit.$v$, 'patience', 'Ecclesiastes', 7, 8),
('Romans 5:3-4', $v$And not only so, but we glory in tribulations also: knowing that tribulation worketh patience; And patience, experience; and experience, hope:$v$, 'patience', 'Romans', 5, 3),
('Galatians 6:9', $v$And let us not be weary in well doing: for in due season we shall reap, if we faint not.$v$, 'patience', 'Galatians', 6, 9),
('Psalm 37:7', $v$Rest in the LORD, and wait patiently for him: fret not thyself because of him who prospereth in his way, because of the man who bringeth wicked devices to pass.$v$, 'patience', 'Psalm', 37, 7),
('Lamentations 3:26', $v$It is good that a man should both hope and quietly wait for the salvation of the LORD.$v$, 'patience', 'Lamentations', 3, 26),
('Hebrews 10:36', $v$For ye have need of patience, that, after ye have done the will of God, ye might receive the promise.$v$, 'patience', 'Hebrews', 10, 36),
('James 1:3-4', $v$Knowing this, that the trying of your faith worketh patience. But let patience have her perfect work, that ye may be perfect and entire, wanting nothing.$v$, 'patience', 'James', 1, 3),
('Proverbs 15:18', $v$A wrathful man stirreth up strife: but he that is slow to anger appeaseth strife.$v$, 'patience', 'Proverbs', 15, 18),
('Proverbs 14:29', $v$He that is slow to wrath is of great understanding: but he that is hasty of spirit exalteth folly.$v$, 'patience', 'Proverbs', 14, 29),
('Romans 8:25', $v$But if we hope for that we see not, then do we with patience wait for it.$v$, 'patience', 'Romans', 8, 25),
('2 Peter 3:9', $v$The Lord is not slack concerning his promise, as some men count slackness; but is longsuffering to us-ward, not willing that any should perish, but that all should come to repentance.$v$, 'patience', '2 Peter', 3, 9),
('1 Thessalonians 5:14', $v$Now we exhort you, brethren, warn them that are unruly, comfort the feebleminded, support the weak, be patient toward all men.$v$, 'patience', '1 Thessalonians', 5, 14),
-- KINDNESS
('Proverbs 11:17', $v$The merciful man doeth good to his own soul: but he that is cruel troubleth his own flesh.$v$, 'kindness', 'Proverbs', 11, 17),
('Proverbs 19:17', $v$He that hath pity upon the poor lendeth unto the LORD; and that which he hath given will he pay him again.$v$, 'kindness', 'Proverbs', 19, 17),
('Luke 6:35', $v$But love ye your enemies, and do good, and lend, hoping for nothing again; and your reward shall be great, and ye shall be the children of the Highest: for he is kind unto the unthankful and to the evil.$v$, 'kindness', 'Luke', 6, 35),
('Micah 6:8', $v$He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?$v$, 'kindness', 'Micah', 6, 8),
('Zechariah 7:9', $v$Thus speaketh the LORD of hosts, saying, Execute true judgment, and shew mercy and compassions every man to his brother:$v$, 'kindness', 'Zechariah', 7, 9),
('Galatians 6:10', $v$As we have therefore opportunity, let us do good unto all men, especially unto them who are of the household of faith.$v$, 'kindness', 'Galatians', 6, 10),
('Proverbs 31:26', $v$She openeth her mouth with wisdom; and in her tongue is the law of kindness.$v$, 'kindness', 'Proverbs', 31, 26),
('1 Thessalonians 5:15', $v$See that none render evil for evil unto any man; but ever follow that which is good, both among yourselves, and to all men.$v$, 'kindness', '1 Thessalonians', 5, 15),
('2 Peter 1:7', $v$And to godliness brotherly kindness; and to brotherly kindness charity.$v$, 'kindness', '2 Peter', 1, 7),
('Ruth 2:12', $v$The LORD recompense thy work, and a full reward be given thee of the LORD God of Israel, under whose wings thou art come to trust.$v$, 'kindness', 'Ruth', 2, 12),
('Proverbs 12:25', $v$Heaviness in the heart of man maketh it stoop: but a good word maketh it glad.$v$, 'kindness', 'Proverbs', 12, 25),
('Ephesians 4:31', $v$Let all bitterness, and wrath, and anger, and clamour, and evil speaking, be put away from you, with all malice:$v$, 'kindness', 'Ephesians', 4, 31),
-- FAITHFULNESS
('Psalm 89:1', $v$I will sing of the mercies of the LORD for ever: with my mouth will I make known thy faithfulness to all generations.$v$, 'faithfulness', 'Psalm', 89, 1),
('1 Corinthians 1:9', $v$God is faithful, by whom ye were called unto the fellowship of his Son Jesus Christ our Lord.$v$, 'faithfulness', '1 Corinthians', 1, 9),
('1 Thessalonians 5:24', $v$Faithful is he that calleth you, who also will do it.$v$, 'faithfulness', '1 Thessalonians', 5, 24),
('Hebrews 10:23', $v$Let us hold fast the profession of our faith without wavering; (for he is faithful that promised;)$v$, 'faithfulness', 'Hebrews', 10, 23),
('Proverbs 28:20', $v$A faithful man shall abound with blessings: but he that maketh haste to be rich shall not be innocent.$v$, 'faithfulness', 'Proverbs', 28, 20),
('Psalm 36:5', $v$Thy mercy, O LORD, is in the heavens; and thy faithfulness reacheth unto the clouds.$v$, 'faithfulness', 'Psalm', 36, 5),
('Psalm 119:90', $v$Thy faithfulness is unto all generations: thou hast established the earth, and it abideth.$v$, 'faithfulness', 'Psalm', 119, 90),
('Matthew 25:21', $v$His lord said unto him, Well done, thou good and faithful servant: thou hast been faithful over a few things, I will make thee ruler over many things: enter thou into the joy of thy lord.$v$, 'faithfulness', 'Matthew', 25, 21),
('1 Corinthians 4:2', $v$Moreover it is required in stewards, that a man be found faithful.$v$, 'faithfulness', '1 Corinthians', 4, 2),
('Psalm 100:5', $v$For the LORD is good; his mercy is everlasting; and his truth endureth to all generations.$v$, 'faithfulness', 'Psalm', 100, 5),
-- SELF-CONTROL
('Proverbs 25:28', $v$He that hath no rule over his own spirit is like a city that is broken down, and without walls.$v$, 'self_control', 'Proverbs', 25, 28),
('1 Corinthians 9:25', $v$And every man that striveth for the mastery is temperate in all things. Now they do it to obtain a corruptible crown; but we an incorruptible.$v$, 'self_control', '1 Corinthians', 9, 25),
('Titus 2:12', $v$Teaching us that, denying ungodliness and worldly lusts, we should live soberly, righteously, and godly, in this present world;$v$, 'self_control', 'Titus', 2, 12),
('1 Peter 5:8', $v$Be sober, be vigilant; because your adversary the devil, as a roaring lion, walketh about, seeking whom he may devour:$v$, 'self_control', '1 Peter', 5, 8),
('Proverbs 16:32', $v$He that is slow to anger is better than the mighty; and he that ruleth his spirit than he that taketh a city.$v$, 'self_control', 'Proverbs', 16, 32),
('1 Thessalonians 5:6', $v$Therefore let us not sleep, as do others; but let us watch and be sober.$v$, 'self_control', '1 Thessalonians', 5, 6),
('1 Thessalonians 5:8', $v$But let us, who are of the day, be sober, putting on the breastplate of faith and love; and for an helmet, the hope of salvation.$v$, 'self_control', '1 Thessalonians', 5, 8),
('Romans 13:14', $v$But put ye on the Lord Jesus Christ, and make not provision for the flesh, to fulfil the lusts thereof.$v$, 'self_control', 'Romans', 13, 14),
('Galatians 5:16', $v$This I say then, Walk in the Spirit, and ye shall not fulfil the lust of the flesh.$v$, 'self_control', 'Galatians', 5, 16),
('2 Timothy 2:22', $v$Flee also youthful lusts: but follow righteousness, faith, charity, peace, with them that call on the Lord out of a pure heart.$v$, 'self_control', '2 Timothy', 2, 22),
('Proverbs 4:23', $v$Keep thy heart with all diligence; for out of it are the issues of life.$v$, 'self_control', 'Proverbs', 4, 23),
('Proverbs 23:12', $v$Apply thine heart unto instruction, and thine ears to the words of knowledge.$v$, 'self_control', 'Proverbs', 23, 12),
-- GENTLENESS
('Isaiah 40:11', $v$He shall feed his flock like a shepherd: he shall gather the lambs with his arm, and carry them in his bosom, and shall gently lead those that are with young.$v$, 'gentleness', 'Isaiah', 40, 11),
('Matthew 11:29', $v$Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls.$v$, 'gentleness', 'Matthew', 11, 29),
('1 Peter 3:15', $v$But sanctify the Lord God in your hearts: and be ready always to give an answer to every man that asketh you a reason of the hope that is in you with meekness and fear:$v$, 'gentleness', '1 Peter', 3, 15),
('Titus 3:2', $v$To speak evil of no man, to be no brawlers, but gentle, shewing all meekness unto all men.$v$, 'gentleness', 'Titus', 3, 2),
('2 Timothy 2:24', $v$And the servant of the Lord must not strive; but be gentle unto all men, apt to teach, patient,$v$, 'gentleness', '2 Timothy', 2, 24),
('Galatians 6:1', $v$Brethren, if a man be overtaken in a fault, ye which are spiritual, restore such an one in the spirit of meekness; considering thyself, lest thou also be tempted.$v$, 'gentleness', 'Galatians', 6, 1),
('James 1:21', $v$Wherefore lay apart all filthiness and superfluity of naughtiness, and receive with meekness the engrafted word, which is able to save your souls.$v$, 'gentleness', 'James', 1, 21),
('Psalm 18:35', $v$Thou hast also given me the shield of thy salvation: and thy right hand hath holden me up, and thy gentleness hath made me great.$v$, 'gentleness', 'Psalm', 18, 35),
('Proverbs 15:1', $v$A soft answer turneth away wrath: but grievous words stir up anger.$v$, 'gentleness', 'Proverbs', 15, 1),
('Matthew 5:5', $v$Blessed are the meek: for they shall inherit the earth.$v$, 'gentleness', 'Matthew', 5, 5),
('Ephesians 4:2', $v$With all lowliness and meekness, with longsuffering, forbearing one another in love;$v$, 'gentleness', 'Ephesians', 4, 2),
-- FORGIVENESS
('Colossians 3:13', $v$Forbearing one another, and forgiving one another, if any man have a quarrel against any: even as Christ forgave you, so also do ye.$v$, 'forgiveness', 'Colossians', 3, 13),
('Matthew 6:14', $v$For if ye forgive men their trespasses, your heavenly Father will also forgive you:$v$, 'forgiveness', 'Matthew', 6, 14),
('Matthew 6:15', $v$But if ye forgive not men their trespasses, neither will your Father forgive your trespasses.$v$, 'forgiveness', 'Matthew', 6, 15),
('Mark 11:25', $v$And when ye stand praying, forgive, if ye have ought against any: that your Father also which is in heaven may forgive you your trespasses.$v$, 'forgiveness', 'Mark', 11, 25),
('Luke 6:37', $v$Judge not, and ye shall not be judged: condemn not, and ye shall not be condemned: forgive, and ye shall be forgiven:$v$, 'forgiveness', 'Luke', 6, 37),
('1 John 2:1', $v$My little children, these things write I unto you, that ye sin not. And if any man sin, we have an advocate with the Father, Jesus Christ the righteous:$v$, 'forgiveness', '1 John', 2, 1),
('Psalm 103:12', $v$As far as the east is from the west, so far hath he removed our transgressions from us.$v$, 'forgiveness', 'Psalm', 103, 12),
('Isaiah 43:25', $v$I, even I, am he that blotteth out thy transgressions for mine own sake, and will not remember thy sins.$v$, 'forgiveness', 'Isaiah', 43, 25),
('Micah 7:18', $v$Who is a God like unto thee, that pardoneth iniquity, and passeth by the transgression of the remnant of his heritage? he retaineth not his anger for ever, because he delighteth in mercy.$v$, 'forgiveness', 'Micah', 7, 18),
('Psalm 130:3-4', $v$If thou, LORD, shouldest mark iniquities, O Lord, who shall stand? But there is forgiveness with thee, that thou mayest be feared.$v$, 'forgiveness', 'Psalm', 130, 3),
('Acts 3:19', $v$Repent ye therefore, and be converted, that your sins may be blotted out, when the times of refreshing shall come from the presence of the Lord;$v$, 'forgiveness', 'Acts', 3, 19),
-- COURAGE
('Joshua 1:9', $v$Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.$v$, 'courage', 'Joshua', 1, 9),
('Joshua 1:7', $v$Only be thou strong and very courageous, that thou mayest observe to do according to all the law, which Moses my servant commanded thee: turn not from it to the right hand or to the left, that thou mayest prosper whithersoever thou goest.$v$, 'courage', 'Joshua', 1, 7),
('Deuteronomy 31:6', $v$Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.$v$, 'courage', 'Deuteronomy', 31, 6),
('1 Chronicles 28:20', $v$And David said to Solomon his son, Be strong and of good courage, and do it: fear not, nor be dismayed: for the LORD God, even my God, will be with thee; he will not fail thee, nor forsake thee, until thou hast finished all the work for the service of the house of the LORD.$v$, 'courage', '1 Chronicles', 28, 20),
('Acts 4:13', $v$Now when they saw the boldness of Peter and John, and perceived that they were unlearned and ignorant men, they marvelled; and they took knowledge of them, that they had been with Jesus.$v$, 'courage', 'Acts', 4, 13),
('Proverbs 28:1', $v$The wicked flee when no man pursueth: but the righteous are bold as a lion.$v$, 'courage', 'Proverbs', 28, 1),
('1 Corinthians 16:13', $v$Watch ye, stand fast in the faith, quit you like men, be strong.$v$, 'courage', '1 Corinthians', 16, 13),
('Ephesians 3:12', $v$In whom we have boldness and access with confidence by the faith of him.$v$, 'courage', 'Ephesians', 3, 12),
('Hebrews 13:6', $v$So that we may boldly say, The Lord is my helper, and I will not fear what man shall do unto me.$v$, 'courage', 'Hebrews', 13, 6),
('Psalm 118:6', $v$The LORD is on my side; I will not fear: what can man do unto me?$v$, 'courage', 'Psalm', 118, 6),
-- REST
('Psalm 23:2', $v$He maketh me to lie down in green pastures: he leadeth me beside the still waters.$v$, 'rest', 'Psalm', 23, 2),
('Psalm 62:1', $v$Truly my soul waiteth upon God: from him cometh my salvation.$v$, 'rest', 'Psalm', 62, 1),
('Psalm 62:5', $v$My soul, wait thou only upon God; for my expectation is from him.$v$, 'rest', 'Psalm', 62, 5),
('Exodus 33:14', $v$And he said, My presence shall go with thee, and I will give thee rest.$v$, 'rest', 'Exodus', 33, 14),
('Jeremiah 6:16', $v$Thus saith the LORD, Stand ye in the ways, and see, and ask for the old paths, where is the good way, and walk therein, and ye shall find rest for your souls. But they said, We will not walk therein.$v$, 'rest', 'Jeremiah', 6, 16),
('Hebrews 4:9-10', $v$There remaineth therefore a rest to the people of God. For he that is entered into his rest, he also hath ceased from his own works, as God did from his.$v$, 'rest', 'Hebrews', 4, 9),
('Isaiah 30:15', $v$For thus saith the Lord GOD, the Holy One of Israel; In returning and rest shall ye be saved; in quietness and in confidence shall be your strength: and ye would not.$v$, 'rest', 'Isaiah', 30, 15),
('Mark 6:31', $v$And he said unto them, Come ye yourselves apart into a desert place, and rest a while: for there were many coming and going, and they had no leisure so much as to eat.$v$, 'rest', 'Mark', 6, 31),
('Psalm 116:7', $v$Return unto thy rest, O my soul; for the LORD hath dealt bountifully with thee.$v$, 'rest', 'Psalm', 116, 7),
('Matthew 11:30', $v$For my yoke is easy, and my burden is light.$v$, 'rest', 'Matthew', 11, 30),
-- NEW BEGINNINGS
('Isaiah 43:19', $v$Behold, I will do a new thing; now it shall spring forth; shall ye not know it? I will even make a way in the wilderness, and rivers in the desert.$v$, 'new_beginnings', 'Isaiah', 43, 19),
('Revelation 21:5', $v$And he that sat upon the throne said, Behold, I make all things new. And he said unto me, Write: for these words are true and faithful.$v$, 'new_beginnings', 'Revelation', 21, 5),
('Isaiah 43:18', $v$Remember ye not the former things, neither consider the things of old.$v$, 'new_beginnings', 'Isaiah', 43, 18),
('Ezekiel 36:26', $v$A new heart also will I give you, and a new spirit will I put within you: and I will take away the stony heart out of your flesh, and I will give you an heart of flesh.$v$, 'new_beginnings', 'Ezekiel', 36, 26),
('Psalm 40:2-3', $v$He brought me up also out of an horrible pit, out of the miry clay, and set my feet upon a rock, and established my goings. And he hath put a new song in my mouth, even praise unto our God: many shall see it, and fear, and shall trust in the LORD.$v$, 'new_beginnings', 'Psalm', 40, 2),
('Philippians 3:13-14', $v$Brethren, I count not myself to have apprehended: but this one thing I do, forgetting those things which are behind, and reaching forth unto those things which are before, I press toward the mark for the prize of the high calling of God in Christ Jesus.$v$, 'new_beginnings', 'Philippians', 3, 13),
('Ephesians 4:22-24', $v$That ye put off concerning the former conversation the old man, which is corrupt according to the deceitful lusts; And be renewed in the spirit of your mind; And that ye put on the new man, which after God is created in righteousness and true holiness.$v$, 'new_beginnings', 'Ephesians', 4, 22),
('Isaiah 61:3', $v$To appoint unto them that mourn in Zion, to give unto them beauty for ashes, the oil of joy for mourning, the garment of praise for the spirit of heaviness; that they might be called trees of righteousness, the planting of the LORD, that he might be glorified.$v$, 'new_beginnings', 'Isaiah', 61, 3),
('Romans 6:4', $v$Therefore we are buried with him by baptism into death: that like as Christ was raised up from the dead by the glory of the Father, even so we also should walk in newness of life.$v$, 'new_beginnings', 'Romans', 6, 4),
('Psalm 51:10', $v$Create in me a clean heart, O God; and renew a right spirit within me.$v$, 'new_beginnings', 'Psalm', 51, 10),
-- SEASONS
('Ecclesiastes 3:1', $v$To every thing there is a season, and a time to every purpose under the heaven:$v$, 'seasons', 'Ecclesiastes', 3, 1),
('Ecclesiastes 3:11', $v$He hath made every thing beautiful in his time: also he hath set the world in their heart, so that no man can find out the work that God maketh from the beginning to the end.$v$, 'seasons', 'Ecclesiastes', 3, 11),
('Genesis 8:22', $v$While the earth remaineth, seedtime and harvest, and cold and heat, and summer and winter, and day and night shall not cease.$v$, 'seasons', 'Genesis', 8, 22),
('Psalm 1:3', $v$And he shall be like a tree planted by the rivers of water, that bringeth forth his fruit in his season; his leaf also shall not wither; and whatsoever he doeth shall prosper.$v$, 'seasons', 'Psalm', 1, 3),
('Jeremiah 17:8', $v$For he shall be as a tree planted by the waters, and that spreadeth out her roots by the river, and shall not see when heat cometh, but her leaf shall be green; and shall not be careful in the year of drought, neither shall cease from yielding fruit.$v$, 'seasons', 'Jeremiah', 17, 8),
('Psalm 104:19', $v$He appointed the moon for seasons: the sun knoweth his going down.$v$, 'seasons', 'Psalm', 104, 19),
('Acts 1:7', $v$And he said unto them, It is not for you to know the times or the seasons, which the Father hath put in his own power.$v$, 'seasons', 'Acts', 1, 7),
('Daniel 2:21', $v$And he changeth the times and the seasons: he removeth kings, and setteth up kings: he giveth wisdom unto the wise, and knowledge to them that know understanding:$v$, 'seasons', 'Daniel', 2, 21),
('Isaiah 55:10-11', $v$For as the rain cometh down, and the snow from heaven, and returneth not thither, but watereth the earth, and maketh it bring forth and bud, that it may give seed to the sower, and bread to the eater: So shall my word be that goeth forth out of my mouth: it shall not return unto me void, but it shall accomplish that which I please, and it shall prosper in the thing whereto I sent it.$v$, 'seasons', 'Isaiah', 55, 10),
('Deuteronomy 11:14', $v$That I will give you the rain of your land in his due season, the first rain and the latter rain, that thou mayest gather in thy corn, and thy wine, and thine oil.$v$, 'seasons', 'Deuteronomy', 11, 14),
('Hosea 10:12', $v$Sow to yourselves in righteousness, reap in mercy; break up your fallow ground: for it is time to seek the LORD, till he come and rain righteousness upon you.$v$, 'seasons', 'Hosea', 10, 12),
-- THANKSGIVING
('Psalm 92:1', $v$It is a good thing to give thanks unto the LORD, and to sing praises unto thy name, O most High:$v$, 'thanksgiving', 'Psalm', 92, 1),
('Psalm 95:2', $v$Let us come before his presence with thanksgiving, and make a joyful noise unto him with psalms.$v$, 'thanksgiving', 'Psalm', 95, 2),
('Psalm 69:30', $v$I will praise the name of God with a song, and will magnify him with thanksgiving.$v$, 'thanksgiving', 'Psalm', 69, 30),
('2 Corinthians 9:15', $v$Thanks be unto God for his unspeakable gift.$v$, 'thanksgiving', '2 Corinthians', 9, 15),
('Ephesians 5:20', $v$Giving thanks always for all things unto God and the Father in the name of our Lord Jesus Christ;$v$, 'thanksgiving', 'Ephesians', 5, 20),
('Colossians 4:2', $v$Continue in prayer, and watch in the same with thanksgiving;$v$, 'thanksgiving', 'Colossians', 4, 2),
('Psalm 50:14', $v$Offer unto God thanksgiving; and pay thy vows unto the most High:$v$, 'thanksgiving', 'Psalm', 50, 14),
('Psalm 116:12', $v$What shall I render unto the LORD for all his benefits toward me?$v$, 'thanksgiving', 'Psalm', 116, 12),
('Psalm 107:8', $v$Oh that men would praise the LORD for his goodness, and for his wonderful works to the children of men!$v$, 'thanksgiving', 'Psalm', 107, 8),
('1 Chronicles 16:34', $v$O give thanks unto the LORD; for he is good; for his mercy endureth for ever.$v$, 'thanksgiving', '1 Chronicles', 16, 34),
-- PRAISE
('Psalm 145:1-2', $v$I will extol thee, my God, O king; and I will bless thy name for ever and ever. Every day will I bless thee; and I will praise thy name for ever and ever.$v$, 'praise', 'Psalm', 145, 1),
('Psalm 146:1-2', $v$Praise ye the LORD. Praise the LORD, O my soul. While I live will I praise the LORD: I will sing praises unto my God while I have any being.$v$, 'praise', 'Psalm', 146, 1),
('Psalm 149:1', $v$Praise ye the LORD. Sing unto the LORD a new song, and his praise in the congregation of saints.$v$, 'praise', 'Psalm', 149, 1),
('Psalm 47:1', $v$O clap your hands, all ye people; shout unto God with the voice of triumph.$v$, 'praise', 'Psalm', 47, 1),
('Psalm 100:1-2', $v$Make a joyful noise unto the LORD, all ye lands. Serve the LORD with gladness: come before his presence with singing.$v$, 'praise', 'Psalm', 100, 1),
('Psalm 63:3-4', $v$Because thy lovingkindness is better than life, my lips shall praise thee. Thus will I bless thee while I live: I will lift up my hands in thy name.$v$, 'praise', 'Psalm', 63, 3),
('Psalm 71:8', $v$Let my mouth be filled with thy praise and with thy honour all the day.$v$, 'praise', 'Psalm', 71, 8),
('Psalm 148:1', $v$Praise ye the LORD. Praise ye the LORD from the heavens: praise him in the heights.$v$, 'praise', 'Psalm', 148, 1),
('Psalm 34:3', $v$O magnify the LORD with me, and let us exalt his name together.$v$, 'praise', 'Psalm', 34, 3),
('Psalm 57:9', $v$I will praise thee, O Lord, among the people: I will sing unto thee among the nations.$v$, 'praise', 'Psalm', 57, 9),
-- TRUST
('Psalm 56:3', $v$What time I am afraid, I will trust in thee.$v$, 'trust', 'Psalm', 56, 3),
('Psalm 9:10', $v$And they that know thy name will put their trust in thee: for thou, LORD, hast not forsaken them that seek thee.$v$, 'trust', 'Psalm', 9, 10),
('Psalm 20:7', $v$Some trust in chariots, and some in horses: but we will remember the name of the LORD our God.$v$, 'trust', 'Psalm', 20, 7),
('Isaiah 26:4', $v$Trust ye in the LORD for ever: for in the LORD JEHOVAH is everlasting strength:$v$, 'trust', 'Isaiah', 26, 4),
('Proverbs 29:25', $v$The fear of man bringeth a snare: but whoso putteth his trust in the LORD shall be safe.$v$, 'trust', 'Proverbs', 29, 25),
('Psalm 118:8', $v$It is better to trust in the LORD than to put confidence in man.$v$, 'trust', 'Psalm', 118, 8),
('Psalm 125:1', $v$They that trust in the LORD shall be as mount Zion, which cannot be removed, but abideth for ever.$v$, 'trust', 'Psalm', 125, 1),
('Psalm 62:8', $v$Trust in him at all times; ye people, pour out your heart before him: God is a refuge for us. Selah.$v$, 'trust', 'Psalm', 62, 8),
('Jeremiah 17:7', $v$Blessed is the man that trusteth in the LORD, and whose hope the LORD is.$v$, 'trust', 'Jeremiah', 17, 7),
('Nahum 1:7', $v$The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.$v$, 'trust', 'Nahum', 1, 7),
('Psalm 84:12', $v$O LORD of hosts, blessed is the man that trusteth in thee.$v$, 'trust', 'Psalm', 84, 12),
-- OVERCOMING FEAR
('Psalm 34:4', $v$I sought the LORD, and he heard me, and delivered me from all my fears.$v$, 'overcoming_fear', 'Psalm', 34, 4),
('Psalm 23:4', $v$Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.$v$, 'overcoming_fear', 'Psalm', 23, 4),
('Psalm 27:3', $v$Though an host should encamp against me, my heart shall not fear: though war should rise against me, in this will I be confident.$v$, 'overcoming_fear', 'Psalm', 27, 3),
('Isaiah 43:1', $v$But now thus saith the LORD that created thee, O Jacob, and he that formed thee, O Israel, Fear not: for I have redeemed thee, I have called thee by thy name; thou art mine.$v$, 'overcoming_fear', 'Isaiah', 43, 1),
('Luke 12:32', $v$Fear not, little flock; for it is your Father's good pleasure to give you the kingdom.$v$, 'overcoming_fear', 'Luke', 12, 32),
('Psalm 46:2', $v$Therefore will not we fear, though the earth be removed, and though the mountains be carried into the midst of the sea;$v$, 'overcoming_fear', 'Psalm', 46, 2),
('Matthew 10:31', $v$Fear ye not therefore, ye are of more value than many sparrows.$v$, 'overcoming_fear', 'Matthew', 10, 31),
('John 14:1', $v$Let not your heart be troubled: ye believe in God, believe also in me.$v$, 'overcoming_fear', 'John', 14, 1),
('Psalm 112:7', $v$He shall not be afraid of evil tidings: his heart is fixed, trusting in the LORD.$v$, 'overcoming_fear', 'Psalm', 112, 7),
('Isaiah 35:4', $v$Say to them that are of a fearful heart, Be strong, fear not: behold, your God will come with vengeance, even God with a recompence; he will come and save you.$v$, 'overcoming_fear', 'Isaiah', 35, 4),
-- PERSEVERANCE
('James 1:12', $v$Blessed is the man that endureth temptation: for when he is tried, he shall receive the crown of life, which the Lord hath promised to them that love him.$v$, 'perseverance', 'James', 1, 12),
('Hebrews 12:1', $v$Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us,$v$, 'perseverance', 'Hebrews', 12, 1),
('Hebrews 12:3', $v$For consider him that endured such contradiction of sinners against himself, lest ye be wearied and faint in your minds.$v$, 'perseverance', 'Hebrews', 12, 3),
('1 Corinthians 15:58', $v$Therefore, my beloved brethren, be ye stedfast, unmoveable, always abounding in the work of the Lord, forasmuch as ye know that your labour is not in vain in the Lord.$v$, 'perseverance', '1 Corinthians', 15, 58),
('2 Timothy 4:7', $v$I have fought a good fight, I have finished my course, I have kept the faith:$v$, 'perseverance', '2 Timothy', 4, 7),
('Philippians 1:6', $v$Being confident of this very thing, that he which hath begun a good work in you will perform it until the day of Jesus Christ:$v$, 'perseverance', 'Philippians', 1, 6),
('Revelation 3:11', $v$Behold, I come quickly: hold that fast which thou hast, that no man take thy crown.$v$, 'perseverance', 'Revelation', 3, 11),
('Galatians 5:1', $v$Stand fast therefore in the liberty wherewith Christ hath made us free, and be not entangled again with the yoke of bondage.$v$, 'perseverance', 'Galatians', 5, 1),
('1 Peter 5:10', $v$But the God of all grace, who hath called us unto his eternal glory by Christ Jesus, after that ye have suffered a while, make you perfect, stablish, strengthen, settle you.$v$, 'perseverance', '1 Peter', 5, 10),
('Luke 18:1', $v$And he spake a parable unto them to this end, that men ought always to pray, and not to faint;$v$, 'perseverance', 'Luke', 18, 1),
('2 Chronicles 15:7', $v$Be ye strong therefore, and let not your hands be weak: for your work shall be rewarded.$v$, 'perseverance', '2 Chronicles', 15, 7),
('Isaiah 40:29', $v$He giveth power to the faint; and to them that have no might he increaseth strength.$v$, 'perseverance', 'Isaiah', 40, 29),
('Micah 7:7', $v$Therefore I will look unto the LORD; I will wait for the God of my salvation: my God will hear me.$v$, 'perseverance', 'Micah', 7, 7),
-- WISDOM
('Proverbs 1:7', $v$The fear of the LORD is the beginning of knowledge: but fools despise wisdom and instruction.$v$, 'wisdom', 'Proverbs', 1, 7),
('Proverbs 9:10', $v$The fear of the LORD is the beginning of wisdom: and the knowledge of the holy is understanding.$v$, 'wisdom', 'Proverbs', 9, 10),
('Proverbs 4:7', $v$Wisdom is the principal thing; therefore get wisdom: and with all thy getting get understanding.$v$, 'wisdom', 'Proverbs', 4, 7),
('Proverbs 2:6', $v$For the LORD giveth wisdom: out of his mouth cometh knowledge and understanding.$v$, 'wisdom', 'Proverbs', 2, 6),
('Proverbs 3:13', $v$Happy is the man that findeth wisdom, and the man that getteth understanding.$v$, 'wisdom', 'Proverbs', 3, 13),
('Colossians 3:16', $v$Let the word of Christ dwell in you richly in all wisdom; teaching and admonishing one another in psalms and hymns and spiritual songs, singing with grace in your hearts to the Lord.$v$, 'wisdom', 'Colossians', 3, 16),
('Psalm 111:10', $v$The fear of the LORD is the beginning of wisdom: a good understanding have all they that do his commandments: his praise endureth for ever.$v$, 'wisdom', 'Psalm', 111, 10),
('Proverbs 8:11', $v$For wisdom is better than rubies; and all the things that may be desired are not to be compared to it.$v$, 'wisdom', 'Proverbs', 8, 11),
('Matthew 7:24', $v$Therefore whosoever heareth these sayings of mine, and doeth them, I will liken him unto a wise man, which built his house upon a rock:$v$, 'wisdom', 'Matthew', 7, 24),
('Psalm 90:12', $v$So teach us to number our days, that we may apply our hearts unto wisdom.$v$, 'wisdom', 'Psalm', 90, 12),
('Proverbs 11:2', $v$When pride cometh, then cometh shame: but with the lowly is wisdom.$v$, 'wisdom', 'Proverbs', 11, 2),
('Ephesians 5:15-16', $v$See then that ye walk circumspectly, not as fools, but as wise, Redeeming the time, because the days are evil.$v$, 'wisdom', 'Ephesians', 5, 15),
-- UNITY
('Psalm 133:1', $v$Behold, how good and how pleasant it is for brethren to dwell together in unity!$v$, 'unity', 'Psalm', 133, 1),
('Ephesians 4:3', $v$Endeavouring to keep the unity of the Spirit in the bond of peace.$v$, 'unity', 'Ephesians', 4, 3),
('1 Corinthians 1:10', $v$Now I beseech you, brethren, by the name of our Lord Jesus Christ, that ye all speak the same thing, and that there be no divisions among you; but that ye be perfectly joined together in the same mind and in the same judgment.$v$, 'unity', '1 Corinthians', 1, 10),
('Romans 15:5-6', $v$Now the God of patience and consolation grant you to be likeminded one toward another according to Christ Jesus: That ye may with one mind and one mouth glorify God, even the Father of our Lord Jesus Christ.$v$, 'unity', 'Romans', 15, 5),
('Colossians 3:14', $v$And above all these things put on charity, which is the bond of perfectness.$v$, 'unity', 'Colossians', 3, 14),
('Ephesians 2:19', $v$Now therefore ye are no more strangers and foreigners, but fellowcitizens with the saints, and of the household of God;$v$, 'unity', 'Ephesians', 2, 19),
('Galatians 3:28', $v$There is neither Jew nor Greek, there is neither bond nor free, there is neither male nor female: for ye are all one in Christ Jesus.$v$, 'unity', 'Galatians', 3, 28),
('Psalm 133:3', $v$As the dew of Hermon, and as the dew that descended upon the mountains of Zion: for there the LORD commanded the blessing, even life for evermore.$v$, 'unity', 'Psalm', 133, 3),
('Amos 3:3', $v$Can two walk together, except they be agreed?$v$, 'unity', 'Amos', 3, 3),
('John 17:21', $v$That they all may be one; as thou, Father, art in me, and I in thee, that they also may be one in us: that the world may believe that thou hast sent me.$v$, 'unity', 'John', 17, 21),
('1 Peter 3:8', $v$Finally, be ye all of one mind, having compassion one of another, love as brethren, be pitiful, be courteous:$v$, 'unity', '1 Peter', 3, 8),
('Philippians 2:2', $v$Fulfil ye my joy, that ye be likeminded, having the same love, being of one accord, of one mind.$v$, 'unity', 'Philippians', 2, 2),
-- LOVE
('1 Corinthians 13:4', $v$Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up,$v$, 'love', '1 Corinthians', 13, 4),
('1 Corinthians 13:7', $v$Beareth all things, believeth all things, hopeth all things, endureth all things.$v$, 'love', '1 Corinthians', 13, 7),
('1 Corinthians 13:8', $v$Charity never faileth: but whether there be prophecies, they shall fail; whether there be tongues, they shall cease; whether there be knowledge, it shall vanish away.$v$, 'love', '1 Corinthians', 13, 8),
('John 13:34', $v$A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another.$v$, 'love', 'John', 13, 34),
('John 13:35', $v$By this shall all men know that ye are my disciples, if ye have love one to another.$v$, 'love', 'John', 13, 35),
('1 John 3:1', $v$Behold, what manner of love the Father hath bestowed upon us, that we should be called the sons of God: therefore the world knoweth us not, because it knew him not.$v$, 'love', '1 John', 3, 1),
('1 John 4:7', $v$Beloved, let us love one another: for love is of God; and every one that loveth is born of God, and knoweth God.$v$, 'love', '1 John', 4, 7),
('1 John 4:19', $v$We love him, because he first loved us.$v$, 'love', '1 John', 4, 19),
('Romans 8:38-39', $v$For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come, Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord.$v$, 'love', 'Romans', 8, 38),
('Song of Solomon 8:7', $v$Many waters cannot quench love, neither can the floods drown it: if a man would give all the substance of his house for love, it would utterly be contemned.$v$, 'love', 'Song of Solomon', 8, 7),
('Matthew 22:37-39', $v$Jesus said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind. This is the first and great commandment. And the second is like unto it, Thou shalt love thy neighbour as thyself.$v$, 'love', 'Matthew', 22, 37),
('1 Corinthians 13:1', $v$Though I speak with the tongues of men and of angels, and have not charity, I am become as sounding brass, or a tinkling cymbal.$v$, 'love', '1 Corinthians', 13, 1),
-- JOY
('Psalm 5:11', $v$But let all those that put their trust in thee rejoice: let them ever shout for joy, because thou defendest them: let them also that love thy name be joyful in thee.$v$, 'joy', 'Psalm', 5, 11),
('Psalm 43:4', $v$Then will I go unto the altar of God, unto God my exceeding joy: yea, upon the harp will I praise thee, O God my God.$v$, 'joy', 'Psalm', 43, 4),
('Psalm 149:5', $v$Let the saints be joyful in glory: let them sing aloud upon their beds.$v$, 'joy', 'Psalm', 149, 5),
('John 15:11', $v$These things have I spoken unto you, that my joy might remain in you, and that your joy might be full.$v$, 'joy', 'John', 15, 11),
('Psalm 97:12', $v$Rejoice in the LORD, ye righteous; and give thanks at the remembrance of his holiness.$v$, 'joy', 'Psalm', 97, 12),
('Ecclesiastes 3:4', $v$A time to weep, and a time to laugh; a time to mourn, and a time to dance;$v$, 'joy', 'Ecclesiastes', 3, 4),
('Psalm 21:6', $v$For thou hast made him most blessed for ever: thou hast made him exceeding glad with thy countenance.$v$, 'joy', 'Psalm', 21, 6),
('Isaiah 61:10', $v$I will greatly rejoice in the LORD, my soul shall be joyful in my God; for he hath clothed me with the garments of salvation, he hath covered me with the robe of righteousness, as a bridegroom decketh himself with ornaments, and as a bride adorneth herself with her jewels.$v$, 'joy', 'Isaiah', 61, 10),
('1 Peter 1:8', $v$Whom having not seen, ye love; in whom, though now ye see him not, yet believing, ye rejoice with joy unspeakable and full of glory:$v$, 'joy', '1 Peter', 1, 8),
('Jude 1:24', $v$Now unto him that is able to keep you from falling, and to present you faultless before the presence of his glory with exceeding joy,$v$, 'joy', 'Jude', 1, 24),
-- PEACE
('Psalm 119:165', $v$Great peace have they which love thy law: and nothing shall offend them.$v$, 'peace', 'Psalm', 119, 165),
('Isaiah 9:6', $v$For unto us a child is born, unto us a son is given: and the government shall be upon his shoulder: and his name shall be called Wonderful, Counsellor, The mighty God, The everlasting Father, The Prince of Peace.$v$, 'peace', 'Isaiah', 9, 6),
('Psalm 34:14', $v$Depart from evil, and do good; seek peace, and pursue it.$v$, 'peace', 'Psalm', 34, 14),
('Matthew 5:9', $v$Blessed are the peacemakers: for they shall be called the children of God.$v$, 'peace', 'Matthew', 5, 9),
('Hebrews 12:14', $v$Follow peace with all men, and holiness, without which no man shall see the Lord:$v$, 'peace', 'Hebrews', 12, 14),
('Mark 9:50', $v$Salt is good: but if the salt have lost his saltness, wherewith will ye season it? Have salt in yourselves, and have peace one with another.$v$, 'peace', 'Mark', 9, 50),
('Psalm 37:11', $v$But the meek shall inherit the earth; and shall delight themselves in the abundance of peace.$v$, 'peace', 'Psalm', 37, 11),
('Isaiah 32:17', $v$And the work of righteousness shall be peace; and the effect of righteousness quietness and assurance for ever.$v$, 'peace', 'Isaiah', 32, 17),
('Philippians 4:9', $v$Those things, which ye have both learned, and received, and heard, and seen in me, do: and the God of peace shall be with you.$v$, 'peace', 'Philippians', 4, 9),
-- HOPE
('Psalm 146:5', $v$Happy is he that hath the God of Jacob for his help, whose hope is in the LORD his God:$v$, 'hope', 'Psalm', 146, 5),
('Romans 15:4', $v$For whatsoever things were written aforetime were written for our learning, that we through patience and comfort of the scriptures might have hope.$v$, 'hope', 'Romans', 15, 4),
('Psalm 130:7', $v$Let Israel hope in the LORD: for with the LORD there is mercy, and with him is plenteous redemption.$v$, 'hope', 'Psalm', 130, 7),
('1 Peter 1:3', $v$Blessed be the God and Father of our Lord Jesus Christ, which according to his abundant mercy hath begotten us again unto a lively hope by the resurrection of Jesus Christ from the dead,$v$, 'hope', '1 Peter', 1, 3),
('Romans 8:24-25', $v$For we are saved by hope: but hope that is seen is not hope: for what a man seeth, why doth he yet hope for? But if we hope for that we see not, then do we with patience wait for it.$v$, 'hope', 'Romans', 8, 24),
('Psalm 71:5', $v$For thou art my hope, O Lord GOD: thou art my trust from my youth.$v$, 'hope', 'Psalm', 71, 5),
('Colossians 1:27', $v$To whom God would make known what is the riches of the glory of this mystery among the Gentiles; which is Christ in you, the hope of glory:$v$, 'hope', 'Colossians', 1, 27),
('1 Timothy 1:1', $v$Paul, an apostle of Jesus Christ by the commandment of God our Saviour, and Lord Jesus Christ, which is our hope;$v$, 'hope', '1 Timothy', 1, 1),
('Titus 1:2', $v$In hope of eternal life, which God, that cannot lie, promised before the world began;$v$, 'hope', 'Titus', 1, 2),
('Psalm 33:22', $v$Let thy mercy, O LORD, be upon us, according as we hope in thee.$v$, 'hope', 'Psalm', 33, 22),
-- STRENGTH
('Psalm 18:32', $v$It is God that girdeth me with strength, and maketh my way perfect.$v$, 'strength', 'Psalm', 18, 32),
('Psalm 28:8', $v$The LORD is their strength, and he is the saving strength of his anointed.$v$, 'strength', 'Psalm', 28, 8),
('Psalm 138:3', $v$In the day when I cried thou answeredst me, and strengthenedst me with strength in my soul.$v$, 'strength', 'Psalm', 138, 3),
('Psalm 18:1', $v$I will love thee, O LORD, my strength.$v$, 'strength', 'Psalm', 18, 1),
('Isaiah 40:30', $v$Even the youths shall faint and be weary, and the young men shall utterly fall:$v$, 'strength', 'Isaiah', 40, 30),
('Zechariah 4:6', $v$Then he answered and spake unto me, saying, This is the word of the LORD unto Zerubbabel, saying, Not by might, nor by power, but by my spirit, saith the LORD of hosts.$v$, 'strength', 'Zechariah', 4, 6),
('2 Chronicles 32:7', $v$Be strong and courageous, be not afraid nor dismayed for the king of Assyria, nor for all the multitude that is with him: for there be more with us than with him:$v$, 'strength', '2 Chronicles', 32, 7),
('Ephesians 3:16', $v$That he would grant you, according to the riches of his glory, to be strengthened with might by his Spirit in the inner man;$v$, 'strength', 'Ephesians', 3, 16),
('Psalm 118:14', $v$The LORD is my strength and song, and is become my salvation.$v$, 'strength', 'Psalm', 118, 14),
-- PROVISION
('Matthew 6:25', $v$Therefore I say unto you, Take no thought for your life, what ye shall eat, or what ye shall drink; nor yet for your body, what ye shall put on. Is not the life more than meat, and the body than raiment?$v$, 'provision', 'Matthew', 6, 25),
('Matthew 6:26', $v$Behold the fowls of the air: for they sow not, neither do they reap, nor gather into barns; yet your heavenly Father feedeth them. Are ye not much better than they?$v$, 'provision', 'Matthew', 6, 26),
('Matthew 7:11', $v$If ye then, being evil, know how to give good gifts unto your children, how much more shall your Father which is in heaven give good things to them that ask him?$v$, 'provision', 'Matthew', 7, 11),
('Psalm 145:16', $v$Thou openest thine hand, and satisfiest the desire of every living thing.$v$, 'provision', 'Psalm', 145, 16),
('Psalm 36:8', $v$They shall be abundantly satisfied with the fatness of thy house; and thou shalt make them drink of the river of thy pleasures.$v$, 'provision', 'Psalm', 36, 8),
('Luke 12:31', $v$But rather seek ye the kingdom of God; and all these things shall be added unto you.$v$, 'provision', 'Luke', 12, 31),
('Proverbs 10:22', $v$The blessing of the LORD, it maketh rich, and he addeth no sorrow with it.$v$, 'provision', 'Proverbs', 10, 22),
('Genesis 22:14', $v$And Abraham called the name of that place Jehovahjireh: as it is said to this day, In the mount of the LORD it shall be seen.$v$, 'provision', 'Genesis', 22, 14),
('2 Corinthians 9:8', $v$And God is able to make all grace abound toward you; that ye, always having all sufficiency in all things, may abound to every good work:$v$, 'provision', '2 Corinthians', 9, 8),
('Psalm 68:19', $v$Blessed be the Lord, who daily loadeth us with benefits, even the God of our salvation. Selah.$v$, 'provision', 'Psalm', 68, 19),
('Haggai 2:8', $v$The silver is mine, and the gold is mine, saith the LORD of hosts.$v$, 'provision', 'Haggai', 2, 8),
('Psalm 37:3', $v$Trust in the LORD, and do good; so shalt thou dwell in the land, and verily thou shalt be fed.$v$, 'provision', 'Psalm', 37, 3),
-- PROTECTION
('Proverbs 30:5', $v$Every word of God is pure: he is a shield unto them that put their trust in him.$v$, 'protection', 'Proverbs', 30, 5),
('Psalm 18:30', $v$As for God, his way is perfect: the word of the LORD is tried: he is a buckler to all those that trust in him.$v$, 'protection', 'Psalm', 18, 30),
('Psalm 5:12', $v$For thou, LORD, wilt bless the righteous; with favour wilt thou compass him as with a shield.$v$, 'protection', 'Psalm', 5, 12),
('Psalm 115:11', $v$Ye that fear the LORD, trust in the LORD: he is their help and their shield.$v$, 'protection', 'Psalm', 115, 11),
('Psalm 3:3', $v$But thou, O LORD, art a shield for me; my glory, and the lifter up of mine head.$v$, 'protection', 'Psalm', 3, 3),
('Psalm 27:5', $v$For in the time of trouble he shall hide me in his pavilion: in the secret of his tabernacle shall he hide me; he shall set me up upon a rock.$v$, 'protection', 'Psalm', 27, 5),
('Psalm 31:20', $v$Thou shalt hide them in the secret of thy presence from the pride of man: thou shalt keep them secretly in a pavilion from the strife of tongues.$v$, 'protection', 'Psalm', 31, 20),
('Proverbs 1:33', $v$But whoso hearkeneth unto me shall dwell safely, and shall be quiet from fear of evil.$v$, 'protection', 'Proverbs', 1, 33),
('Psalm 91:14', $v$Because he hath set his love upon me, therefore will I deliver him: I will set him on high, because he hath known my name.$v$, 'protection', 'Psalm', 91, 14),
('Psalm 121:5', $v$The LORD is thy keeper: the LORD is thy shade upon thy right hand.$v$, 'protection', 'Psalm', 121, 5),
-- GUIDANCE
('Psalm 48:14', $v$For this God is our God for ever and ever: he will be our guide even unto death.$v$, 'guidance', 'Psalm', 48, 14),
('Proverbs 16:9', $v$A man's heart deviseth his way: but the LORD directeth his steps.$v$, 'guidance', 'Proverbs', 16, 9),
('Psalm 25:4', $v$Shew me thy ways, O LORD; teach me thy paths.$v$, 'guidance', 'Psalm', 25, 4),
('Psalm 25:5', $v$Lead me in thy truth, and teach me: for thou art the God of my salvation; on thee do I wait all the day.$v$, 'guidance', 'Psalm', 25, 5),
('Psalm 31:3', $v$For thou art my rock and my fortress; therefore for thy name's sake lead me, and guide me.$v$, 'guidance', 'Psalm', 31, 3),
('Isaiah 48:17', $v$Thus saith the LORD, thy Redeemer, the Holy One of Israel; I am the LORD thy God which teacheth thee to profit, which leadeth thee by the way that thou shouldest go.$v$, 'guidance', 'Isaiah', 48, 17),
('Psalm 16:7', $v$I will bless the LORD, who hath given me counsel: my reins also instruct me in the night seasons.$v$, 'guidance', 'Psalm', 16, 7),
('John 10:27', $v$My sheep hear my voice, and I know them, and they follow me:$v$, 'guidance', 'John', 10, 27),
('Psalm 73:24', $v$Thou shalt guide me with thy counsel, and afterward receive me to glory.$v$, 'guidance', 'Psalm', 73, 24),
('Psalm 119:133', $v$Order my steps in thy word: and let not any iniquity have dominion over me.$v$, 'guidance', 'Psalm', 119, 133),
('1 Corinthians 2:9', $v$But as it is written, Eye hath not seen, nor ear heard, neither have entered into the heart of man, the things which God hath prepared for them that love him.$v$, 'guidance', '1 Corinthians', 2, 9),
-- VICTORY
('1 Corinthians 15:54', $v$So when this corruptible shall have put on incorruption, and this mortal shall have put on immortality, then shall be brought to pass the saying that is written, Death is swallowed up in victory.$v$, 'victory', '1 Corinthians', 15, 54),
('Deuteronomy 28:7', $v$The LORD shall cause thine enemies that rise up against thee to be smitten before thy face: they shall come out against thee one way, and flee before thee seven ways.$v$, 'victory', 'Deuteronomy', 28, 7),
('Psalm 44:5', $v$Through thee will we push down our enemies: through thy name will we tread them under that rise up against us.$v$, 'victory', 'Psalm', 44, 5),
('Isaiah 41:11', $v$Behold, all they that were incensed against thee shall be ashamed and confounded: they shall be as nothing; and they that strive with thee shall perish.$v$, 'victory', 'Isaiah', 41, 11),
('Psalm 108:13', $v$Through God we shall do valiantly: for he it is that shall tread down our enemies.$v$, 'victory', 'Psalm', 108, 13),
('Exodus 15:2', $v$The LORD is my strength and song, and he is become my salvation: he is my God, and I will prepare him an habitation; my father's God, and I will exalt him.$v$, 'victory', 'Exodus', 15, 2),
('Romans 16:20', $v$And the God of peace shall bruise Satan under your feet shortly. The grace of our Lord Jesus Christ be with you. Amen.$v$, 'victory', 'Romans', 16, 20),
('Psalm 20:6', $v$Now know I that the LORD saveth his anointed; he will hear him from his holy heaven with the saving strength of his right hand.$v$, 'victory', 'Psalm', 20, 6),
('2 Samuel 22:40', $v$For thou hast girded me with strength to battle: them that rose up against me hast thou subdued under me.$v$, 'victory', '2 Samuel', 22, 40),
('Psalm 41:11', $v$By this I know that thou favourest me, because mine enemy doth not triumph over me.$v$, 'victory', 'Psalm', 41, 11)
ON CONFLICT (reference) DO NOTHING;
