-- ALTER transactions TABLE FOR AUDIT AND RECIPIENT VISIBILITY
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS recipient_name TEXT;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS recipient_phone TEXT;
