-- Migration: 20260710_expand_bible_quiz_questions.sql
-- Adds 65+ diverse Bible quiz questions across all categories

INSERT INTO quiz_questions (question, options, correct_answer, difficulty, category, scripture_reference, points, style)
VALUES
-- OLD TESTAMENT HISTORY
('How many days and nights did Noah''s flood rain upon the earth?',
 '["7 days","40 days and 40 nights","150 days","1 year"]', 1, 'Medium', 'History', 'Genesis 7:12', 10, 'multiple_choice'),
('Who was the first king of Israel?',
 '["David","Solomon","Saul","Samuel"]', 2, 'Easy', 'History', '1 Samuel 9:17', 10, 'multiple_choice'),
('In which city was the Tower of Babel built?',
 '["Jerusalem","Babylon","Ur","Nineveh"]', 1, 'Hard', 'History', 'Genesis 11:9', 15, 'multiple_choice'),
('How old was Methuselah when he died?',
 '["900","969","777","856"]', 1, 'Hard', 'History', 'Genesis 5:27', 15, 'multiple_choice'),
('Which tribe of Israel was Moses from?',
 '["Judah","Benjamin","Levi","Simeon"]', 2, 'Medium', 'History', 'Exodus 2:1', 10, 'multiple_choice'),
('Who was the judge of Israel who defeated the Midianites with 300 men?',
 '["Samson","Joshua","Gideon","Deborah"]', 2, 'Medium', 'History', 'Judges 7:7', 10, 'multiple_choice'),
('How many years did the Israelites wander in the desert?',
 '["20","30","40","50"]', 2, 'Easy', 'History', 'Numbers 14:33', 10, 'multiple_choice'),
-- NEW TESTAMENT
('How many disciples did Jesus choose?',
 '["10","11","12","13"]', 2, 'Easy', 'NT', 'Luke 6:13', 10, 'multiple_choice'),
('In which city was Jesus born?',
 '["Nazareth","Jerusalem","Bethlehem","Jericho"]', 2, 'Easy', 'NT', 'Luke 2:4-7', 10, 'multiple_choice'),
('Who baptized Jesus?',
 '["Peter","John the Baptist","Andrew","Elijah"]', 1, 'Easy', 'NT', 'Matthew 3:13-17', 10, 'multiple_choice'),
('Which disciple walked on water with Jesus?',
 '["John","James","Peter","Andrew"]', 2, 'Medium', 'NT', 'Matthew 14:29', 10, 'multiple_choice'),
('What was the name of the sea Jesus calmed?',
 '["Red Sea","Dead Sea","Sea of Galilee","Mediterranean Sea"]', 2, 'Medium', 'NT', 'Mark 4:39', 10, 'multiple_choice'),
('What did Jesus use to feed 5,000 people?',
 '["5 loaves and 2 fish","7 loaves and 3 fish","3 loaves and 5 fish","10 loaves and 2 fish"]', 0, 'Easy', 'Miracles', 'John 6:9', 10, 'multiple_choice'),
-- MIRACLES
('What did Jesus turn water into at the wedding in Cana?',
 '["Milk","Wine","Oil","Honey"]', 1, 'Easy', 'Miracles', 'John 2:9', 10, 'multiple_choice'),
('Which prophet called down fire from heaven at Mount Carmel?',
 '["Elisha","Isaiah","Elijah","Jeremiah"]', 2, 'Medium', 'Miracles', '1 Kings 18:38', 10, 'multiple_choice'),
('Who did Jesus raise from the dead in Bethany?',
 '["Jairus","Lazarus","The widow''s son","Tabitha"]', 1, 'Easy', 'Miracles', 'John 11:43-44', 10, 'multiple_choice'),
('How many days was Lazarus in the tomb before Jesus raised him?',
 '["1","2","3","4"]', 3, 'Hard', 'Miracles', 'John 11:39', 15, 'multiple_choice'),
('What miracle did God perform for Joshua in the battle of Gibeon?',
 '["Made the walls fall","Stopped the sun and moon","Parted the river","Sent fire"]', 1, 'Hard', 'Miracles', 'Joshua 10:13', 15, 'multiple_choice'),
('What animal spoke to Balaam?',
 '["A serpent","A donkey","A lion","An eagle"]', 1, 'Medium', 'Miracles', 'Numbers 22:28', 10, 'multiple_choice'),
-- PROPHECY
('Which prophet predicted Jesus would be born of a virgin?',
 '["Micah","Jeremiah","Isaiah","Ezekiel"]', 2, 'Medium', 'Prophecy', 'Isaiah 7:14', 10, 'multiple_choice'),
('Which prophet said the Messiah would be born in Bethlehem?',
 '["Isaiah","Micah","Amos","Hosea"]', 1, 'Medium', 'Prophecy', 'Micah 5:2', 10, 'multiple_choice'),
('How many major prophets are in the Old Testament?',
 '["4","5","6","7"]', 1, 'Hard', 'Prophecy', NULL, 15, 'multiple_choice'),
('Which prophet was swallowed by a great fish?',
 '["Elijah","Elisha","Jonah","Nahum"]', 2, 'Easy', 'Prophecy', 'Jonah 1:17', 10, 'multiple_choice'),
('What did the prophet Ezekiel see in his famous valley vision?',
 '["A burning bush","The valley of dry bones","A wheel within a wheel","A ladder to heaven"]', 1, 'Hard', 'Prophecy', 'Ezekiel 37:1-14', 15, 'multiple_choice'),
-- SCRIPTURE
('What language was the New Testament primarily written in?',
 '["Hebrew","Latin","Aramaic","Greek"]', 3, 'Hard', 'Scripture', NULL, 15, 'multiple_choice'),
('How many books are in the New Testament?',
 '["24","27","30","39"]', 1, 'Easy', 'Scripture', NULL, 10, 'multiple_choice'),
('Who wrote the book of Revelation?',
 '["Paul","Peter","James","John"]', 3, 'Medium', 'Scripture', 'Revelation 1:1', 10, 'multiple_choice'),
('Which gospel begins with "In the beginning was the Word"?',
 '["Matthew","Mark","Luke","John"]', 3, 'Medium', 'Scripture', 'John 1:1', 10, 'multiple_choice'),
('Who wrote most of the Psalms?',
 '["Solomon","David","Moses","Asaph"]', 1, 'Easy', 'Scripture', NULL, 10, 'multiple_choice'),
('What is the shortest verse in the Bible?',
 '["God is love","Fear not","Jesus wept","Amen"]', 2, 'Easy', 'Scripture', 'John 11:35', 10, 'multiple_choice'),
('What is the shortest chapter in the Bible?',
 '["Psalm 150","Psalm 117","John 11","Obadiah 1"]', 1, 'Medium', 'Scripture', NULL, 10, 'multiple_choice'),
('How many books are in the entire Bible?',
 '["60","63","66","72"]', 2, 'Easy', 'General', NULL, 10, 'multiple_choice'),
('Which language was most of the Old Testament originally written in?',
 '["Greek","Latin","Aramaic","Hebrew"]', 3, 'Hard', 'Scripture', NULL, 15, 'multiple_choice'),
-- PEOPLE
('What was the name of Ruth''s mother-in-law?',
 '["Orpah","Naomi","Hannah","Rahab"]', 1, 'Easy', 'People', 'Ruth 1:2', 10, 'multiple_choice'),
('Who was the first woman mentioned in the Bible?',
 '["Rahab","Ruth","Eve","Sarah"]', 2, 'Easy', 'People', 'Genesis 2:23', 10, 'multiple_choice'),
('Who was Jacob''s firstborn son?',
 '["Joseph","Reuben","Judah","Simeon"]', 1, 'Medium', 'People', 'Genesis 29:32', 10, 'multiple_choice'),
('What was the apostle Paul''s original name?',
 '["Simon","Barnabas","Saul","Stephen"]', 2, 'Easy', 'People', 'Acts 13:9', 10, 'multiple_choice'),
('Which apostle denied Jesus three times?',
 '["John","James","Judas","Peter"]', 3, 'Easy', 'People', 'Luke 22:61', 10, 'multiple_choice'),
('Who was the first martyr recorded in the New Testament?',
 '["James","John","Stephen","Philip"]', 2, 'Medium', 'People', 'Acts 7:59', 10, 'multiple_choice'),
('Who was Timothy''s mother?',
 '["Lydia","Eunice","Priscilla","Lois"]', 1, 'Hard', 'People', '2 Timothy 1:5', 15, 'multiple_choice'),
('Who was thrown into the den of lions?',
 '["Shadrach","Daniel","Joseph","Jeremiah"]', 1, 'Easy', 'People', 'Daniel 6:16', 10, 'multiple_choice'),
('Who was known as the father of faith in the New Testament?',
 '["Moses","Noah","Abraham","Isaac"]', 2, 'Easy', 'People', 'Romans 4:16', 10, 'multiple_choice'),
('Which disciple betrayed Jesus for 30 pieces of silver?',
 '["Peter","Thomas","Judas Iscariot","Bartholomew"]', 2, 'Easy', 'NT', 'Matthew 26:15', 10, 'multiple_choice'),
-- LAW
('How many commandments did God give Moses on Mount Sinai?',
 '["5","10","12","15"]', 1, 'Easy', 'Law', 'Exodus 20', 10, 'multiple_choice'),
('What is the first commandment?',
 '["Honor your parents","You shall have no other gods before Me","You shall not kill","Remember the Sabbath"]', 1, 'Easy', 'Law', 'Exodus 20:3', 10, 'multiple_choice'),
('On what material were the Ten Commandments written?',
 '["Papyrus","Gold tablets","Stone tablets","Bronze plates"]', 2, 'Easy', 'Law', 'Exodus 31:18', 10, 'multiple_choice'),
('What is the greatest commandment according to Jesus?',
 '["Do not commit adultery","Love your neighbor as yourself","Love the Lord your God with all your heart","Honor your father and mother"]', 2, 'Easy', 'Law', 'Matthew 22:37-38', 10, 'multiple_choice'),
-- ANGELS
('Which angel announced the birth of Jesus to Mary?',
 '["Michael","Raphael","Gabriel","Uriel"]', 2, 'Easy', 'Angels', 'Luke 1:26', 10, 'multiple_choice'),
('Which angel is described as the archangel in the Bible?',
 '["Gabriel","Michael","Raphael","Seraphim"]', 1, 'Medium', 'Angels', 'Jude 1:9', 10, 'multiple_choice'),
('What did the angel say to the shepherds when Jesus was born?',
 '["Go to Bethlehem at once","Fear not! I bring you good news of great joy","Prepare the way of the Lord","Behold the Lamb of God"]', 1, 'Easy', 'Angels', 'Luke 2:10', 10, 'multiple_choice'),
-- GENERAL
('Which book of the Bible comes first?',
 '["Job","Psalms","Genesis","Exodus"]', 2, 'Easy', 'General', NULL, 10, 'multiple_choice'),
('In which river was Jesus baptized?',
 '["Jordan River","Nile River","Euphrates River","Kidron Brook"]', 0, 'Easy', 'NT', 'Matthew 3:13', 10, 'multiple_choice'),
('What does the name Jesus mean?',
 '["Son of God","Lamb of God","God saves","Prince of Peace"]', 2, 'Medium', 'People', 'Matthew 1:21', 10, 'multiple_choice'),
('What was the name of the garden where Adam and Eve lived?',
 '["Garden of Gethsemane","Garden of Eden","Garden of Paradise","Mount Sinai"]', 1, 'Easy', 'OT', 'Genesis 2:8', 10, 'multiple_choice'),
('How many men were thrown into the fiery furnace in Babylon?',
 '["2","3","4","7"]', 1, 'Easy', 'History', 'Daniel 3:24', 10, 'multiple_choice'),
('What type of branch did people use to welcome Jesus into Jerusalem?',
 '["Olive branches","Vine branches","Palm branches","Cedar branches"]', 2, 'Easy', 'NT', 'John 12:13', 10, 'multiple_choice'),
('On which day of the week did Jesus rise from the dead?',
 '["Friday","Saturday","Sunday","Monday"]', 2, 'Easy', 'NT', 'Mark 16:9', 10, 'multiple_choice'),
('How many days did Jesus fast in the wilderness?',
 '["20","30","40","50"]', 2, 'Easy', 'NT', 'Matthew 4:2', 10, 'multiple_choice'),
('What did Pilate do to signify he found no fault in Jesus?',
 '["Tore his robe","Washed his hands","Bowed his head","Left the courtroom"]', 1, 'Medium', 'NT', 'Matthew 27:24', 10, 'multiple_choice'),
('Which book of the Bible contains the Levitical laws?',
 '["Genesis","Exodus","Leviticus","Numbers"]', 2, 'Medium', 'Law', NULL, 10, 'multiple_choice')
ON CONFLICT DO NOTHING;
